Add customer issue smart action
ForestAdmin/forest-live-demo-e-commerce pull request #2
Opened 2023-03-13 11:18 UTC by lionelbzv

Plug a smart action on issue detail to allow users to easier adding a "customer issue support" relative to the issue

2023-03-21 08:43 UTC, SteveBunlon commented on forest/customer-issue.js
> +const { customerIssue } = require('../models');
This line is not needed

2023-03-21 08:44 UTC, SteveBunlon requested changes
This is neaaaat 🤩

2023-03-23 12:50 UTC, lionelbzv commented on forest/customer-issue.js
> +const { customerIssue } = require('../models');
done

2023-03-28 08:16 UTC, SteveBunlon approved these changes

2023-03-28 08:16 UTC, merged